### ISSUE TITLE
看文档显示必须要创建一个cce，不能支持自建的k8s集群吗？

### ISSUE THREAD

**Issue by mxq0923** [baidubce/baiducloud-cce-cni-driver#2]
## 前置条件

需要具备一个可用的百度云 CCE 集群。见[创建一个 CCE 集群](https://cloud.baidu.com/doc/CCE/s/zjxpoqohb).

这样是不是不支持自建的k8s集群？

**Comment by YL1028K** [comment]
是的。
这个是基于百度云CCE的网络基础开发的CNI相关部分，核心的IPAM都是调百度接口实现的。

**Comment by YL1028K** [comment]
> 是的。 这个是基于百度云CCE的网络基础开发的CNI相关部分，核心的IPAM都是调百度接口实现的。

或者你在使用百度云的网络
